//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuBanYeTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class agent
    {
        public agent()
        {
            this.delegates = new HashSet<@delegate>();
            this.manages = new HashSet<manage>();
        }
    
        public int person_id { get; set; }
        public string profession { get; set; }
        public System.DateTime register_date { get; set; }
        public Nullable<System.DateTime> valid_date { get; set; }
        public int trade_number { get; set; }
    
        public virtual person person { get; set; }
        public virtual ICollection<@delegate> delegates { get; set; }
        public virtual ICollection<manage> manages { get; set; }
    }
}
