//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuBanYeTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class @delegate
    {
        public int member { get; set; }
        public int agent { get; set; }
        public int house { get; set; }
        public System.DateTime date { get; set; }
        public string messages { get; set; }
        public string state { get; set; }
    
        public virtual agent agent1 { get; set; }
        public virtual house house1 { get; set; }
        public virtual member member1 { get; set; }
    }
}
