//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuBanYeTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HouseManagementDBEntities : DbContext
    {
        public HouseManagementDBEntities()
            : base("name=HouseManagementDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<address> addresses { get; set; }
        public DbSet<agent> agents { get; set; }
        public DbSet<@delegate> delegates { get; set; }
        public DbSet<house> houses { get; set; }
        public DbSet<manage> manages { get; set; }
        public DbSet<member> members { get; set; }
        public DbSet<person> people { get; set; }
        public DbSet<photo> photos { get; set; }
        public DbSet<renthouse> renthouses { get; set; }
        public DbSet<salehouse> salehouses { get; set; }
        public DbSet<setting> settings { get; set; }
    }
}
