//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuBanYeTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class house
    {
        public house()
        {
            this.delegates = new HashSet<@delegate>();
            this.manages = new HashSet<manage>();
            this.photos = new HashSet<photo>();
        }
    
        public int house_id { get; set; }
        public string levels { get; set; }
        public Nullable<int> area { get; set; }
        public string orientation { get; set; }
        public string types { get; set; }
        public string decoration { get; set; }
        public byte[] thumbnails { get; set; }
        public Nullable<byte> room { get; set; }
        public Nullable<byte> hall { get; set; }
        public Nullable<byte> toilet { get; set; }
        public Nullable<int> address { get; set; }
        public Nullable<int> member { get; set; }
    
        public virtual address address1 { get; set; }
        public virtual ICollection<@delegate> delegates { get; set; }
        public virtual member member1 { get; set; }
        public virtual ICollection<manage> manages { get; set; }
        public virtual ICollection<photo> photos { get; set; }
        public virtual renthouse renthouse { get; set; }
        public virtual salehouse salehouse { get; set; }
    }
}
