//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuBanYeTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public member()
        {
            this.delegates = new HashSet<@delegate>();
            this.houses = new HashSet<house>();
        }
    
        public int person_id { get; set; }
        public string identity_number { get; set; }
    
        public virtual ICollection<@delegate> delegates { get; set; }
        public virtual ICollection<house> houses { get; set; }
        public virtual person person { get; set; }
    }
}
