//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuBanYeTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class renthouse
    {
        public renthouse()
        {
            this.settings = new HashSet<setting>();
        }
    
        public int house_id { get; set; }
        public string types { get; set; }
        public Nullable<int> payment { get; set; }
        public string description { get; set; }
    
        public virtual house house { get; set; }
        public virtual ICollection<setting> settings { get; set; }
    }
}
