//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuBanYeTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class salehouse
    {
        public int house_id { get; set; }
        public string types { get; set; }
        public Nullable<int> price { get; set; }
        public string developer { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<int> property_costs { get; set; }
        public Nullable<System.DateTime> build_date { get; set; }
        public string description { get; set; }
    
        public virtual house house { get; set; }
    }
}
